source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'

inhibit_all_warnings!

target :WebApiClient do
	pod 'AFNetworking',				'~> 2.6'
	pod 'AFgzipRequestSerializer',  '~> 0.0.2'
	pod 'BRCocoaLumberjack',		'~> 2.0'
	pod 'BREnvironment',			'~> 1.2'
	pod 'BRLocalize',				'~> 0.9'
	pod 'ImageEffects',				'~> 1.0'
	pod 'MAObjCRuntime', 			'~> 0.0.1'
	pod 'Masonry',					'~> 0.6'
	pod 'PINCache',					'~> 2.0'
	pod 'RestKit/ObjectMapping',	'~> 0.27'
	pod 'SOCKit',             		'~> 1.1'
	pod 'TransformerKit/String',    '~> 0.5'

	target :WebApiClientTests do
		pod 'OCHamcrest',			'~> 4.1'
		pod 'OCMock',				'~> 3.1'
		pod 'CocoaHTTPServer',		'~> 2.3'
		
		# Pull in a patched version of RoutingHTTPServer
		pod 'RoutingHTTPServer', 	:git => 'https://github.com/Blue-Rocket/RoutingHTTPServer.git', :branch => 'feature/unsafe-unretained-connection-fix'
	end

end
